complete -c teip -n "__fish_use_subcommand" -s g -d 'Bypassing lines that match the regular expression <pattern>'
complete -c teip -n "__fish_use_subcommand" -s f -d 'Bypassing these white-space separated fields'
complete -c teip -n "__fish_use_subcommand" -s d -d 'Use <delimiter> for field delimiter of -f'
complete -c teip -n "__fish_use_subcommand" -s D -d 'Use regular expression <pattern> for field delimiter of -f'
complete -c teip -n "__fish_use_subcommand" -s c -d 'Bypassing these characters'
complete -c teip -n "__fish_use_subcommand" -s l -d 'Bypassing those lines'
complete -c teip -n "__fish_use_subcommand" -s e -d 'Execute <string> on another process that will receive identical standard input as the teip, and numbers given by the result are used as line numbers for bypassing'
complete -c teip -n "__fish_use_subcommand" -s A -d 'Alias of -e \'grep -n -A <number> <pattern>\''
complete -c teip -n "__fish_use_subcommand" -s B -d 'Alias of -e \'grep -n -B <number> <pattern>\''
complete -c teip -n "__fish_use_subcommand" -s C -d 'Alias of -e \'grep -n -C <number> <pattern>\''
complete -c teip -n "__fish_use_subcommand" -l sed -d 'Alias of -e \'sed -n "<pattern>="\''
complete -c teip -n "__fish_use_subcommand" -l awk -d 'Alias of -e \'awk "<pattern>{print NR}"\''
complete -c teip -n "__fish_use_subcommand" -l completion
complete -c teip -n "__fish_use_subcommand" -s o -d '-g bypasses only matched parts'
complete -c teip -n "__fish_use_subcommand" -s G -d '-g interprets Oniguruma regular expressions.'
complete -c teip -n "__fish_use_subcommand" -l csv -d '-f interprets <list> as field number of a CSV according to RFC 4180, instead of white-space separated fields'
complete -c teip -n "__fish_use_subcommand" -l unko
complete -c teip -n "__fish_use_subcommand" -s s -d 'Execute new command for each bypassed chunk'
complete -c teip -n "__fish_use_subcommand" -l chomp -d 'Command spawned by -s receives standard input without trailing newlines'
complete -c teip -n "__fish_use_subcommand" -s v -d 'Invert the range of bypassing'
complete -c teip -n "__fish_use_subcommand" -s z -d 'Line delimiter is NUL instead of a newline'
complete -c teip -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c teip -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
