name: Benchmark

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Benchmark for each functions
      run: cargo bench

  files:
    name: Benchmark with a large file
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        include:
          - name: perf_regex_match
            cmd: teip -og '.*sshd' < test_secure
          - name: perf_onig_match
            cmd: teip -Gog '.*sshd' < test_secure
          - name: perf_convert_date
            cmd: teip -c1-15 -- date -f- +%s < test_secure
          - name: mem_usage
            cmd: teip -e 'grep -n -C 3 admin' -- sed 's/./@/g' < test_secure
          - name: mem_usage_worst
            cmd: teip -e 'awk "NR==1{print NR}"' -- sed 's/./@/g' < test_secure
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install musl-tools autoconf autotools-dev valgrind

    - name: Build
      run: |
        rustup target add x86_64-unknown-linux-musl
        CFLAGS="-fPIE" CC="musl-gcc -static" cargo build --verbose --release --target x86_64-unknown-linux-musl
        mv target/x86_64-unknown-linux-musl/release/teip target/release

    - name: Prepare benchmarking
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
        sudo dpkg -i ./hyperfine_1.9.0_amd64.deb
        wget https://github.com/greymd/test_files/raw/master/logs/test_secure.gz
        gzip -d ./test_secure.gz

        # Debugging
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Benchmark for a large file
      if: contains(matrix.name, 'perf')
      run: |
        hyperfine --export-json ./${{ matrix.name }}.json "./target/release/${{ matrix.cmd }}"

    - name: Save benchmark result for processing time
      if: contains(matrix.name, 'perf')
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.name }}
        path: ./${{ matrix.name }}.json

    - name: Show benchmark result for processing time
      if: contains(matrix.name, 'perf')
      run: |
        cat ./${{ matrix.name }}.json

    - name: Benchmark for memory usage
      if: contains(matrix.name, 'mem')
      timeout-minutes: 10
      run: |
        valgrind --tool=massif --time-unit=ms --massif-out-file=${{matrix.name}}.txt ./target/release/${{ matrix.cmd }} > tmp

    - name: Save benchmark result for memory usage
      if: contains(matrix.name, 'mem')
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.name }}
        path: ./${{ matrix.name }}.txt

    - name: Show benchmark result for memory usage
      if: contains(matrix.name, 'mem')
      run: |
        ms_print ./${{ matrix.name }}.txt | awk 'NR==1,/Detailed snapshots/{print}'
