name: Tests for Windows

on:
  push:
    branches:
      - main
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: test
    runs-on: ${{matrix.os}}
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: exe

    steps:
      - uses: actions/checkout@v3
      - name: Build the release target
        run: |
          rustup target add ${{ matrix.target }}
          choco install llvm
          cargo build --features oniguruma --release --verbose --target x86_64-pc-windows-msvc
          # => target\x86_64-pc-windows-msvc\release\teip.exe will be created
      - name: Run tests
        timeout-minutes: 10
        run: cargo test --verbose --features oniguruma
